DeepDiveIntoSSD/testshell/SsdControlService.cpp, DeepDiveIntoSSD/testshell/SsdControlServiceTest.cpp, DeepDiveIntoSSD/testshell/testshell.vcxproj
=> Add testcases

DeepDiveIntoSSD/testshell/SsdControlService.cpp
=> 탐장 string 추가

DeepDiveIntoSSD/ssd/ArgManager.cpp, DeepDiveIntoSSD/ssd/Ssd.cpp
1) stoi 에서 invalid 일 때 false 를 반환하도록 하였습니다.
2) argument 가 0 일 때 예외처리 하였습니다.
=> stoi 예외 처리 추가 및 코드가 정상적으로 종료되도록 수정

DeepDiveIntoSSD/testshell/WriteCommandMapper.cpp
=> fix input check error

DeepDiveIntoSSD/testshell/ISsdController.h, DeepDiveIntoSSD/testshell/IoC.cpp, DeepDiveIntoSSD/testshell/IoC.h, DeepDiveIntoSSD/testshell/MockSsdControler.h, DeepDiveIntoSSD/testshell/ReadCommand.cpp, DeepDiveIntoSSD/testshell/ReadCommand.h, DeepDiveIntoSSD/testshell/ReadCommandMapper.cpp, DeepDiveIntoSSD/testshell/ReadCommandMapper.h, DeepDiveIntoSSD/testshell/ReadCommandMapperTest.cpp, DeepDiveIntoSSD/testshell/ReadCommandTest.cpp, DeepDiveIntoSSD/testshell/ReadView.cpp, DeepDiveIntoSSD/testshell/ReadView.h, DeepDiveIntoSSD/testshell/ReadViewTest.cpp, DeepDiveIntoSSD/testshell/SsdControlService.cpp, DeepDiveIntoSSD/testshell/SsdController.cpp, DeepDiveIntoSSD/testshell/SsdController.h, DeepDiveIntoSSD/testshell/SsdReadResult.h, DeepDiveIntoSSD/testshell/SsdReadService.cpp, DeepDiveIntoSSD/testshell/SsdReadService.h, DeepDiveIntoSSD/testshell/SsdReadServiceTest.cpp, DeepDiveIntoSSD/testshell/SsdWriteServiceTest.cpp, DeepDiveIntoSSD/testshell/main.cpp, DeepDiveIntoSSD/testshell/testshell.vcxproj, DeepDiveIntoSSD/testshell/testshell.vcxproj.filters
=> ReadCommand 구현 완료

DeepDiveIntoSSD/testshell/FullReadCommand.cpp, DeepDiveIntoSSD/testshell/FullReadCommand.h, DeepDiveIntoSSD/testshell/FullReadCommandMapper.cpp, DeepDiveIntoSSD/testshell/FullReadCommandMapper.h, DeepDiveIntoSSD/testshell/FullReadView.cpp, DeepDiveIntoSSD/testshell/FullReadView.h, DeepDiveIntoSSD/testshell/IoC.cpp, DeepDiveIntoSSD/testshell/IoC.h, DeepDiveIntoSSD/testshell/SsdFullReadService.cpp, DeepDiveIntoSSD/testshell/SsdFullReadService.h, DeepDiveIntoSSD/testshell/testshell.vcxproj, DeepDiveIntoSSD/testshell/testshell.vcxproj.filters
=> FullRead 구현 완료

DeepDiveIntoSSD/testshell/FullWriteAndReadCompareTestScriptCommand.cpp, DeepDiveIntoSSD/testshell/FullWriteAndReadCompareTestScriptCommand.h, DeepDiveIntoSSD/testshell/FullWriteAndReadCompareTestScriptCommandMapper.cpp, DeepDiveIntoSSD/testshell/FullWriteAndReadCompareTestScriptCommandMapper.h, DeepDiveIntoSSD/testshell/FullWriteAndReadCompareTestScriptService.cpp, DeepDiveIntoSSD/testshell/FullWriteAndReadCompareTestScriptService.h, DeepDiveIntoSSD/testshell/IView.h, DeepDiveIntoSSD/testshell/IoC.cpp, DeepDiveIntoSSD/testshell/IoC.h, DeepDiveIntoSSD/testshell/TestScriptView.cpp, DeepDiveIntoSSD/testshell/TestScriptView.h, DeepDiveIntoSSD/testshell/testshell.vcxproj, DeepDiveIntoSSD/testshell/testshell.vcxproj.filters
1_FullWriteAndReadCompare 구현 완료
=> 1_FullWriteAndReadCompare 구현 완료

DeepDiveIntoSSD/testshell/IoC.cpp, DeepDiveIntoSSD/testshell/IoC.h, DeepDiveIntoSSD/testshell/WriteReadAgingTestScriptCommand.cpp, DeepDiveIntoSSD/testshell/WriteReadAgingTestScriptCommand.h, DeepDiveIntoSSD/testshell/WriteReadAgingTestScriptCommandMapper.cpp, DeepDiveIntoSSD/testshell/WriteReadAgingTestScriptCommandMapper.h, DeepDiveIntoSSD/testshell/WriteReadAgingTestScriptService.cpp, DeepDiveIntoSSD/testshell/WriteReadAgingTestScriptService.h, DeepDiveIntoSSD/testshell/testshell.vcxproj, DeepDiveIntoSSD/testshell/testshell.vcxproj.filters
=> 3_WriteReadAging 구현 완료

DeepDiveIntoSSD/testshell/EraseCommand.cpp, DeepDiveIntoSSD/testshell/EraseCommand.h, DeepDiveIntoSSD/testshell/EraseCommandMapper.cpp, DeepDiveIntoSSD/testshell/EraseCommandMapper.h, DeepDiveIntoSSD/testshell/EraseRangeCommandMapper.cpp, DeepDiveIntoSSD/testshell/EraseRangeCommandMapper.h, DeepDiveIntoSSD/testshell/EraseView.cpp, DeepDiveIntoSSD/testshell/EraseView.h, DeepDiveIntoSSD/testshell/ISsdController.h, DeepDiveIntoSSD/testshell/IoC.cpp, DeepDiveIntoSSD/testshell/IoC.h, DeepDiveIntoSSD/testshell/MockSsdControler.h, DeepDiveIntoSSD/testshell/ParsingUtil.cpp, DeepDiveIntoSSD/testshell/ParsingUtil.h, DeepDiveIntoSSD/testshell/SsdController.cpp, DeepDiveIntoSSD/testshell/SsdController.h, DeepDiveIntoSSD/testshell/SsdEraseResult.cpp, DeepDiveIntoSSD/testshell/SsdEraseResult.h, DeepDiveIntoSSD/testshell/SsdEraseService.cpp, DeepDiveIntoSSD/testshell/SsdEraseService.h, DeepDiveIntoSSD/testshell/main.cpp, DeepDiveIntoSSD/testshell/testshell.vcxproj, DeepDiveIntoSSD/testshell/testshell.vcxproj.filters
* Erase 및 Erase Range 커맨드 구현 완료하였습니다.
=> Erase, Erase Range Command 기능 구현 완료

DeepDiveIntoSSD/testshell/EraseCommandMapper.cpp, DeepDiveIntoSSD/testshell/EraseCommandMapper.h, DeepDiveIntoSSD/testshell/EraseRangeCommandMapper.cpp, DeepDiveIntoSSD/testshell/EraseRangeCommandMapper.h
아래와 같이 리뷰해주신 두 부분 수정 완료하였습니다.
* erase 시 size는 음수 값을 가질 수 있도록 수정
* endLba가 startLba보다 작을 수 있도록 수정
=> [TestShell] Erase 커맨드 수정 - 음수 처리 관련

DeepDiveIntoSSD/testshell/Logger.h, DeepDiveIntoSSD/testshell/testshell.vcxproj, DeepDiveIntoSSD/testshell/testshell.vcxproj.filters
=> Add Logger feature

DeepDiveIntoSSD/testshell/EraseCommandMapper.cpp, DeepDiveIntoSSD/testshell/EraseCommandMapperTest.cpp, DeepDiveIntoSSD/testshell/main.cpp, DeepDiveIntoSSD/testshell/testshell.vcxproj, DeepDiveIntoSSD/testshell/testshell.vcxproj.filters
음수 size가 방향만 -가 되고 Write Amount가 유지되도록 수정했습니다.
테스트 코드 추가하였으며, 최신 main 브랜치의 내용을 merge 하였습니다.
=> [TestShell] Erase 기능 수정

DeepDiveIntoSSD/testshell/Logger.h
=> update .log -> .zip

DeepDiveIntoSSD/testshell/EraseAndWriteAgingTestScriptCommand.cpp, DeepDiveIntoSSD/testshell/EraseAndWriteAgingTestScriptCommand.h, DeepDiveIntoSSD/testshell/EraseAndWriteAgingTestScriptCommandMapper.cpp, DeepDiveIntoSSD/testshell/EraseAndWriteAgingTestScriptCommandMapper.h, DeepDiveIntoSSD/testshell/EraseAndWriteAgingTestScriptService.cpp, DeepDiveIntoSSD/testshell/EraseAndWriteAgingTestScriptService.h, DeepDiveIntoSSD/testshell/IoC.cpp, DeepDiveIntoSSD/testshell/IoC.h, DeepDiveIntoSSD/testshell/TestShellApplication.cpp, DeepDiveIntoSSD/testshell/WriteReadAgingTestScriptService.cpp, DeepDiveIntoSSD/testshell/main.cpp, DeepDiveIntoSSD/testshell/testshell.vcxproj, DeepDiveIntoSSD/testshell/testshell.vcxproj.filters
4_EraseAndWriteAging 구현 완료하였습니다.
=> TestScript - 4_EraseAndWriteAging 구현 완료

DeepDiveIntoSSD/ssd/ArgManager.cpp, DeepDiveIntoSSD/ssd/ArgManager.h, DeepDiveIntoSSD/ssd/CommandBuffer.cpp, DeepDiveIntoSSD/ssd/CommandBuffer.h, DeepDiveIntoSSD/ssd/FileIO.cpp, DeepDiveIntoSSD/ssd/FileIO.h, DeepDiveIntoSSD/ssd/Ssd.cpp, DeepDiveIntoSSD/ssd/Ssd.h, DeepDiveIntoSSD/ssd/ssd.vcxproj, DeepDiveIntoSSD/ssd/ssd.vcxproj.filters
command buffer 부분 erase 및 write 구현 하였습니다.
Read 부분은 추가 구현이 필요합니다.
추가로 algorithm 부분은 따로 호출 없이 맨 뒤로 push 되도록 하였습니다.
algorithm 구현이 완료되면 수정 필요합니다.
=> commandBuffer Write 및 Erase 부분 구현. Read 추가 필요

DeepDiveIntoSSD/testshell/FlushCommand.cpp, DeepDiveIntoSSD/testshell/FlushCommand.h, DeepDiveIntoSSD/testshell/FlushCommandMapper.cpp, DeepDiveIntoSSD/testshell/FlushCommandMapper.h, DeepDiveIntoSSD/testshell/FlushView.cpp, DeepDiveIntoSSD/testshell/FlushView.h, DeepDiveIntoSSD/testshell/ISsdController.h, DeepDiveIntoSSD/testshell/IoC.cpp, DeepDiveIntoSSD/testshell/IoC.h, DeepDiveIntoSSD/testshell/MockSsdControler.h, DeepDiveIntoSSD/testshell/SsdController.cpp, DeepDiveIntoSSD/testshell/SsdController.h, DeepDiveIntoSSD/testshell/SsdFlushResult.cpp, DeepDiveIntoSSD/testshell/SsdFlushResult.h, DeepDiveIntoSSD/testshell/SsdFlushService.cpp, DeepDiveIntoSSD/testshell/SsdFlushService.h, DeepDiveIntoSSD/testshell/testshell.vcxproj, DeepDiveIntoSSD/testshell/testshell.vcxproj.filters
Flush Command 구현완료하였습니다. 확인 부탁드려요~!
=> Flush Command 구현 완료

DeepDiveIntoSSD/ssd/ArgManager.cpp, DeepDiveIntoSSD/ssd/ArgManager.h, DeepDiveIntoSSD/ssd/Ssd.cpp
=> Flush 기능 구현

DeepDiveIntoSSD/ssd/Ssd.cpp, DeepDiveIntoSSD/ssd/Ssd.h
flush 함수 분리 및 read enable
현재 read 는 바로 ssd_nand.txt 를 읽도록 되어 있어서 flush 되지 않으면 기존 값을 읽게 되어 있습니다.
=> flush 함수 분리

DeepDiveIntoSSD/ssd/SSDReadWriteTest.cpp, DeepDiveIntoSSD/ssd/Ssd.h, DeepDiveIntoSSD/ssd/main.cpp
SSD 부분을 singleton 으로 refactoring 하였습니다.
=> apply singleton

DeepDiveIntoSSD/testshell/EraseView.cpp, DeepDiveIntoSSD/testshell/EraseView.h, DeepDiveIntoSSD/testshell/FlushView.cpp, DeepDiveIntoSSD/testshell/FlushView.h, DeepDiveIntoSSD/testshell/HelpView.cpp, DeepDiveIntoSSD/testshell/HelpView.h, DeepDiveIntoSSD/testshell/ReadView.cpp, DeepDiveIntoSSD/testshell/ReadView.h, DeepDiveIntoSSD/testshell/TestScriptView.cpp, DeepDiveIntoSSD/testshell/TestScriptView.h
=> 출력 문자열을 상수화

.gitignore, DeepDiveIntoSSD/testshell/EraseRangeCommandMapper.cpp
erase_range 버그를 수정하였습니다.
(startLBA, endLBA가 항상 바뀌어들어가는 문제 수정)
=> erase_range 버그 수정

DeepDiveIntoSSD/testshell-core/AbstractScriptCommand.h, DeepDiveIntoSSD/testshell-core/RunnerApplication.cpp, DeepDiveIntoSSD/testshell/shell_scripts.txt
Runner 테스트 중간에 Fail 발생하면 중단되도록 수정하였습니다.
=> Runner 테스트 중간에 Fail 발생하면 중단되도록 수정

DeepDiveIntoSSD/testshell-core/RunnerApplication.cpp
=> 파일 없는 에러 출력 시 string 깨지는 것 수정
